name: 'dbt_test7'
version: '1.0.0'
config-version: 2
profile: dbt_test7
model-paths: ["models"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
test
some errors
models:
  dbt_test7:
    staging:
      +materialized: view
    +materialized: table