dbt_test7:
  target: dev
  outputs:
  done in vs
    dev:
      type: bigquery
      method: service-account
      project: prd-dagen
      dataset: ecom1
      threads: 4
      keyfile: ./keyfile.json